apiVersion: backstage.io/v1alpha1
kind: Dataset
metadata:
  name: dataset3
  namespace: default
  title: "Customer Segmentation Dataset"
  description: "Training dataset for customer segmentation"
spec:
  type: "training"
  format: "CSV"
  owner: "data-team"
